# Generated by Django 5.2.3 on 2025-07-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0004_salesitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='status',
        ),
        migrations.RemoveField(
            model_name='products',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='tax_amount',
        ),
        migrations.AddField(
            model_name='products',
            name='f_restock',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.BigIntegerField(default=0),
        ),
    ]
