# Generated by Django 5.2.3 on 2025-07-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0005_remove_category_status_remove_products_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sale',
            field=models.BigIntegerField(default=0),
        ),
    ]
