# Generated by Django 5.2.3 on 2025-07-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0007_alter_products_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='code',
            field=models.CharField(max_length=100),
        ),
    ]
