# Generated by Django 5.2.3 on 2025-07-11 15:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0008_alter_products_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='f_restock',
        ),
        migrations.RemoveField(
            model_name='products',
            name='sale',
        ),
        migrations.CreateModel(
            name='Restock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restock_date', models.DateTimeField(auto_now=True)),
                ('sale', models.BigIntegerField(default=0)),
                ('f_restock', models.BigIntegerField(default=0)),
                ('f_restock_before', models.BigIntegerField(default=0)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posApp.products')),
            ],
        ),
    ]
