# Generated by Django 5.2.3 on 2025-08-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0009_remove_products_f_restock_remove_products_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sale',
            field=models.BigIntegerField(default=0),
        ),
    ]
