# Generated by Django 5.2.3 on 2025-08-09 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0010_products_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='sale',
        ),
    ]
