# Generated by Django 5.2.6 on 2025-10-15 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0011_remove_products_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category_before',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_previous', to='posApp.category'),
        ),
    ]
