# Generated by Django 5.2.6 on 2025-10-15 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0012_products_category_before'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category_before',
        ),
    ]
