# Generated by Django 6.0.6 on 2026-07-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0013_remove_products_category_before'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='modal',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sales',
            name='profit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='salesitems',
            name='modal',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='salesitems',
            name='profit',
            field=models.FloatField(default=0),
        ),
    ]
